version: '3.8'

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "6432:5432"

  app:
    build: .
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "8080:8080"

volumes:
  db_data:
